import type { Question, ServiceId } from '../lib/types';
export const questionSets = {
  branding: {
    '1': [
      {
        id: 'branding-1-1',
        label: 'What do you need?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'New brand',
          'Brand refresh',
          'Logo only',
          'Stationery or marketing assets',
          'Not sure',
        ],
      },
      {
        id: 'branding-1-2',
        label: 'Which items are required?',
        type: 'multi',
        optional: false,
        stage: 1,
        options: [
          'Logo',
          'Business card',
          'Letterhead',
          'Email signature',
          'Social templates',
          'Brand guide',
          'Other standard listed items',
        ],
      },
      {
        id: 'branding-1-3',
        label: 'Do you have an existing identity?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Complete identity', 'Logo only', 'Some assets', 'No identity'],
      },
      {
        id: 'branding-1-4',
        label: 'What best describes the business?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'New business',
          'Existing business changing direction',
          'New product or service',
          'Personal brand',
          'Nonprofit or community organisation',
        ],
      },
      {
        id: 'branding-1-5',
        label: 'When would you like to begin?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'As soon as available',
          'Within one month',
          'Within one to three months',
          'Later',
          'Not sure',
        ],
      },
      {
        id: 'branding-1-6',
        label: 'Do you also need another FinTaxTech service?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Website', 'Mobile app', 'Prompt service', 'None', 'Not sure'],
      },
      {
        id: 'branding-1-7',
        label: 'How should we continue?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Email', 'WhatsApp', 'Zoom call'],
      },
      {
        id: 'branding-1-8',
        label: 'Anything else we should know?',
        type: 'text',
        optional: true,
        stage: 1,
      },
    ],
    '2': [
      {
        id: 'branding-2-1',
        label: 'Which branding deliverables are required?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Logo',
          'Business card',
          'Letterhead',
          'Email signature',
          'Social templates',
          'Brand guide',
          'Marketing assets',
        ],
      },
      {
        id: 'branding-2-2',
        label: 'Which logo structure suits the name?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Wordmark',
          'Lettermark or monogram',
          'Symbol plus name',
          'Emblem or badge',
          'Not sure',
        ],
      },
      {
        id: 'branding-2-3',
        label: 'Which qualities should the identity express?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Professional',
          'Bold',
          'Approachable',
          'Innovative',
          'Premium',
          'Playful',
          'Dependable',
          'Technical',
          'Minimal',
        ],
        max: 3,
      },
      {
        id: 'branding-2-4',
        label: 'Which visual direction feels closest?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Minimal geometric',
          'Editorial',
          'Organic',
          'Technical',
          'Heritage',
          'Expressive',
          'Not sure',
        ],
        max: 2,
      },
      {
        id: 'branding-2-5',
        label: 'Which colour direction is preferred?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Monochrome',
          'Cool colours',
          'Warm colours',
          'Muted',
          'Bold contrast',
          'Open to recommendation',
        ],
      },
      {
        id: 'branding-2-6',
        label: 'Which typography direction is preferred?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Modern sans serif',
          'Traditional serif',
          'Humanist',
          'Technical',
          'Mixed',
          'Open to recommendation',
        ],
      },
      {
        id: 'branding-2-7',
        label: 'What should the logo contain?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Business name only',
          'Name and symbol',
          'Initials',
          'Tagline',
          'Open to recommendation',
        ],
      },
      {
        id: 'branding-2-8',
        label: 'Where will the identity be used?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Website',
          'App',
          'Social media',
          'Print',
          'Signage',
          'Packaging',
          'Presentations',
        ],
      },
      {
        id: 'branding-2-9',
        label: 'Which final files are needed?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Web images',
          'Print files',
          'Vector files',
          'Editable source where included',
          'Favicon or app icon',
          'Brand guide',
        ],
      },
      {
        id: 'branding-2-10',
        label: 'What should the design avoid?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Gradients',
          'Complex detail',
          'Literal symbols',
          'Playful typography',
          'Nothing specific',
          'Add a detail',
        ],
      },
      {
        id: 'branding-2-11',
        label: 'Additional direction',
        type: 'text',
        optional: true,
        stage: 2,
      },
    ],
  },
  websites: {
    '1': [
      {
        id: 'websites-1-1',
        label: 'What type of project is this?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'New business website',
          'Complete redesign and rebuild',
          'Ecommerce website',
          'Web application',
          'Campaign or landing page',
          'Not sure',
        ],
      },
      {
        id: 'websites-1-2',
        label: 'What is the main purpose?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Generate enquiries',
          'Explain services',
          'Sell products',
          'Take bookings',
          'Provide an online tool',
          'Publish information',
          'Not sure',
        ],
      },
      {
        id: 'websites-1-3',
        label: 'How many content pages are expected?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['1', '2–5', '6–10', 'More than 10', 'Not sure'],
      },
      {
        id: 'websites-1-4',
        label: 'Which functions are needed?',
        type: 'multi',
        optional: false,
        stage: 1,
        options: [
          'Contact links',
          'Forms',
          'Ecommerce',
          'Bookings',
          'Accounts',
          'Dashboard',
          'Integrations',
          'Content management',
          'Not sure',
        ],
      },
      {
        id: 'websites-1-5',
        label: 'What assets already exist?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Complete content and brand assets',
          'Content only',
          'Brand assets only',
          'Some assets',
          'No assets',
        ],
      },
      {
        id: 'websites-1-6',
        label: 'Which additional services may be needed?',
        type: 'multi',
        optional: false,
        stage: 1,
        options: [
          'Branding',
          'Content creation',
          'Analytics',
          'SEO setup',
          'Ongoing support',
          'None',
          'Not sure',
        ],
      },
      {
        id: 'websites-1-7',
        label: 'When would you like to begin?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'As soon as available',
          'Within one month',
          'Within one to three months',
          'Later',
          'Not sure',
        ],
      },
      {
        id: 'websites-1-8',
        label: 'How should we continue?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Email', 'WhatsApp', 'Zoom call'],
      },
      {
        id: 'websites-1-9',
        label: 'Anything else we should know?',
        type: 'text',
        optional: true,
        stage: 1,
      },
    ],
    '2': [
      {
        id: 'websites-2-1',
        label: 'What should visitors do?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Contact the business',
          'Request a quote',
          'Call or message',
          'Book',
          'Buy',
          'Register or sign in',
          'Download information',
          'Visit a location',
        ],
        max: 2,
      },
      {
        id: 'websites-2-2',
        label: 'Which pages are needed?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Home',
          'About',
          'Services',
          'FAQ',
          'Contact',
          'Selected work',
          'Legal pages',
          'Custom page',
        ],
      },
      {
        id: 'websites-2-3',
        label: 'Who will provide the content?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Customer provides all approved content',
          'FinTaxTech creates all content as an additional service',
        ],
      },
      {
        id: 'websites-2-4',
        label: 'Which visual assets are available?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Complete set',
          'Logo and some images',
          'Logo only',
          'Images only',
          'No assets',
          'Will provide later',
        ],
      },
      {
        id: 'websites-2-5',
        label: 'Which visual direction is preferred?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Minimal',
          'Corporate',
          'Editorial',
          'Bold',
          'Friendly',
          'Premium',
          'Technical',
          'Open to recommendation',
        ],
      },
      {
        id: 'websites-2-6',
        label: 'Which contact methods should appear?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Email',
          'Telephone',
          'WhatsApp',
          'Contact form where supported',
          'Booking link',
          'Address',
          'Social channels',
        ],
      },
      {
        id: 'websites-2-7',
        label: 'Which integrations are required?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Analytics',
          'Maps',
          'Booking platform',
          'Email marketing',
          'Payments',
          'CRM',
          'Social feeds',
          'Other',
          'None',
        ],
      },
      {
        id: 'websites-2-8',
        label: 'Who will own the accounts?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Customer already owns them',
          'Customer will create them',
          'FinTaxTech should guide account creation',
          'Not sure',
        ],
      },
      {
        id: 'websites-2-9',
        label: 'For a redesign, what happens to the current site?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Replace all content and design',
          'Retain selected approved content only',
          'Archive privately',
          'Not sure',
        ],
        when: {
          id: 'websites-1-1',
          includes: 'Complete redesign and rebuild',
        },
      },
      {
        id: 'websites-2-10',
        label: 'What support is expected after launch?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Defect warranty only',
          'Occasional quoted changes',
          'Maintenance proposal',
          'Training or handover',
          'Not sure',
        ],
      },
      {
        id: 'websites-2-11',
        label: 'Additional requirements',
        type: 'text',
        optional: true,
        stage: 2,
      },
    ],
  },
  'mobile-apps': {
    '1': [
      {
        id: 'mobile-apps-1-1',
        label: 'What type of project is this?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'New app',
          'Complete redesign and rebuild',
          'Companion app',
          'Internal business app',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-1-2',
        label: 'Which platforms are required?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Android', 'iOS', 'Both', 'Not sure'],
      },
      {
        id: 'mobile-apps-1-3',
        label: 'Is there a technology preference?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Native', 'Kotlin Multiplatform', 'Flutter', 'Open to recommendation'],
      },
      {
        id: 'mobile-apps-1-4',
        label: 'Who will use the app?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Customers',
          'Staff',
          'Partners',
          'Members',
          'Marketplace buyers and sellers',
          'Mixed roles',
        ],
      },
      {
        id: 'mobile-apps-1-5',
        label: 'Which main features are expected?',
        type: 'multi',
        optional: false,
        stage: 1,
        options: [
          'Accounts',
          'Payments',
          'Subscriptions',
          'Bookings',
          'Messaging',
          'Maps or location',
          'Camera or media',
          'Notifications',
          'Offline use',
          'Integrations',
        ],
      },
      {
        id: 'mobile-apps-1-6',
        label: 'Is a back end or admin area required?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Yes', 'No', 'Unsure'],
      },
      {
        id: 'mobile-apps-1-7',
        label: 'What design material exists?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Complete designs',
          'Wireframes',
          'Brand only',
          'Idea or written brief',
          'Nothing yet',
        ],
      },
      {
        id: 'mobile-apps-1-8',
        label: 'What stage is the project at?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Idea', 'Requirements prepared', 'Prototype', 'Existing app to rebuild'],
      },
      {
        id: 'mobile-apps-1-9',
        label: 'When would you like to begin?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'As soon as available',
          'Within one month',
          'Within one to three months',
          'Later',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-1-10',
        label: 'How should we continue?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Email', 'WhatsApp', 'Zoom call'],
      },
      {
        id: 'mobile-apps-1-11',
        label: 'Anything else we should know?',
        type: 'text',
        optional: true,
        stage: 1,
      },
    ],
    '2': [
      {
        id: 'mobile-apps-2-1',
        label: 'How will users access the app?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'No account',
          'Email and password',
          'Telephone and code',
          'Social sign-in',
          'Organisation-issued access',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-2-2',
        label: 'Which user roles are required?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Customer',
          'Staff',
          'Administrator',
          'Supplier',
          'Professional or provider',
          'Other defined role',
        ],
      },
      {
        id: 'mobile-apps-2-3',
        label: 'How will the product earn revenue?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Free',
          'Paid download',
          'Subscription',
          'In-app purchase',
          'Transaction fee',
          'Advertising',
          'Business-funded internal tool',
          'Undecided',
        ],
      },
      {
        id: 'mobile-apps-2-4',
        label: 'Which data will the app handle?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Profiles',
          'Messages',
          'Documents',
          'Images or video',
          'Location',
          'Payments',
          'Health or other sensitive data',
          'Minimal data',
        ],
      },
      {
        id: 'mobile-apps-2-5',
        label: 'How will users communicate?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'No messaging',
          'In-app chat',
          'Email triggers',
          'SMS',
          'Push notifications',
          'Video or voice',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-2-6',
        label: 'Which device capabilities are needed?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Camera',
          'Microphone',
          'Location',
          'Bluetooth',
          'Biometrics',
          'Notifications',
          'File storage',
          'None',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-2-7',
        label: 'Which external services are required?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Payments',
          'Maps',
          'Analytics',
          'CRM',
          'Cloud storage',
          'Social login',
          'existing API',
          'None',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-2-8',
        label: 'What should administrators manage?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Users',
          'Content',
          'Orders or bookings',
          'Payments',
          'Reports',
          'Moderation',
          'Configuration',
          'Basic support only',
          'Not sure',
        ],
      },
      {
        id: 'mobile-apps-2-9',
        label: 'Which assets are available?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Brand and designs',
          'Brand only',
          'Designs only',
          'Requirements',
          'Prototype',
          'No assets',
        ],
      },
      {
        id: 'mobile-apps-2-10',
        label: 'Additional requirements',
        type: 'text',
        optional: true,
        stage: 2,
      },
    ],
  },
  'prompt-services': {
    '1': [
      {
        id: 'prompt-services-1-1',
        label: 'What type of content is involved?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Business document',
          'Technical document',
          'Report',
          'Website content',
          'App content',
          'Marketing material',
          'Research material',
          'Other',
        ],
      },
      {
        id: 'prompt-services-1-2',
        label: 'What source material is available?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Final PDF',
          'draft PDF',
          'several PDFs',
          'Scanned document',
          'Source will be provided later',
        ],
      },
      {
        id: 'prompt-services-1-3',
        label: 'What should FinTaxTech do?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Create',
          'Summarise',
          'Rewrite',
          'Extract',
          'Restructure',
          'Convert',
          'Review and recommend',
          'Not sure',
        ],
      },
      {
        id: 'prompt-services-1-4',
        label: 'How long is the source material?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['1–10 pages', '11–30', '31–75', 'More than 75', 'Not sure'],
      },
      {
        id: 'prompt-services-1-5',
        label: 'Which output is required?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Document',
          'Presentation',
          'Structured text',
          'Summary',
          'Table',
          'Multiple formats',
          'Not sure',
        ],
      },
      {
        id: 'prompt-services-1-6',
        label: 'How much human review is expected?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Standard review',
          'Detailed editorial review',
          'Fact and source checking where possible',
          'Not sure',
        ],
      },
      {
        id: 'prompt-services-1-7',
        label: 'When is it needed?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'Urgent subject to availability',
          'Within one week',
          'Within two weeks',
          'Flexible',
          'Not sure',
        ],
      },
      {
        id: 'prompt-services-1-8',
        label: 'Does the material contain sensitive information?',
        type: 'single',
        optional: false,
        stage: 1,
        options: [
          'No',
          'Personal data',
          'Commercial information',
          'Regulated or highly sensitive information',
          'Unsure',
        ],
      },
      {
        id: 'prompt-services-1-9',
        label: 'How should we continue?',
        type: 'single',
        optional: false,
        stage: 1,
        options: ['Email', 'WhatsApp', 'Zoom call'],
      },
      {
        id: 'prompt-services-1-10',
        label: 'Anything else we should know?',
        type: 'text',
        optional: true,
        stage: 1,
      },
    ],
    '2': [
      {
        id: 'prompt-services-2-1',
        label: 'What is the primary output?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Summary',
          'Rewritten document',
          'Extracted data',
          'New structured content',
          'Analysis',
          'Recommendations',
          'Presentation-ready copy',
        ],
      },
      {
        id: 'prompt-services-2-2',
        label: 'Who is the audience?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'General public',
          'Customers',
          'Management',
          'Technical team',
          'Investors',
          'Regulators or professionals',
          'Internal staff',
        ],
      },
      {
        id: 'prompt-services-2-3',
        label: 'Which tone is required?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Plain',
          'Professional',
          'Formal',
          'Persuasive',
          'Technical',
          'Friendly',
          'Match the source',
        ],
      },
      {
        id: 'prompt-services-2-4',
        label: 'How closely should the output follow the source?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Strictly source-based',
          'Reorganise without changing meaning',
          'Allow careful expansion',
          'Create a new structure from the source',
        ],
      },
      {
        id: 'prompt-services-2-5',
        label: 'How much detail is required?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Executive summary',
          'Concise',
          'Standard',
          'Detailed',
          'Comprehensive subject to scope',
        ],
      },
      {
        id: 'prompt-services-2-6',
        label: 'How should source references appear?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Page references',
          'Footnotes',
          'Inline citations',
          'Source list',
          'No references required',
          'Not sure',
        ],
      },
      {
        id: 'prompt-services-2-7',
        label: 'Which formats are required?',
        type: 'multi',
        optional: false,
        stage: 2,
        options: [
          'Markdown',
          'Word',
          'PDF',
          'PowerPoint',
          'Spreadsheet or table',
          'Plain text',
          'More than one',
        ],
      },
      {
        id: 'prompt-services-2-8',
        label: 'What presentation level is expected?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'Content only',
          'Clean formatting',
          'Branded formatting',
          'Presentation-ready design',
        ],
      },
      {
        id: 'prompt-services-2-9',
        label: 'How should uncertain or missing information be handled?',
        type: 'single',
        optional: false,
        stage: 2,
        options: ['Flag it', 'Ask before continuing', 'State assumptions', 'Omit it', 'Not sure'],
      },
      {
        id: 'prompt-services-2-10',
        label: 'Does the customer have authority to supply and process the material?',
        type: 'single',
        optional: false,
        stage: 2,
        options: ['Yes', 'Permission pending', 'Unsure'],
      },
      {
        id: 'prompt-services-2-11',
        label: 'Does the material contain sensitive content?',
        type: 'single',
        optional: false,
        stage: 2,
        options: [
          'None',
          'Personal',
          'Confidential commercial',
          'Health or regulated',
          'Legally privileged',
          'Unsure',
        ],
      },
      {
        id: 'prompt-services-2-12',
        label: 'Additional requirements',
        type: 'text',
        optional: true,
        stage: 2,
      },
    ],
  },
} satisfies Record<ServiceId, Record<'1' | '2', Question[]>>;
